name: projucts_helper
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/gorge4.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/1.mp3 
    - assets/2.mp3 
    - assets/3.m4a 
    - assets/4.m4a 
    - assets/5.m4a 
    - assets/6.mp3 
    - assets/7.m4a 
    - assets/8.m4a 
    - assets/9.m4a 
    - assets/10.mp3
    - assets/11.mp3
    - assets/12.m4a
    - assets/13.m4a
    - assets/14.mp3
    - assets/15.m4a
    - assets/16.m4a
    - assets/17.m4a
    - assets/18.mp3
    - assets/19.m4a
    - assets/20.m4a
    - assets/21.m4a
    - assets/22.m4a
    - assets/23.m4a
    - assets/24.m4a
    - assets/25.m4a
    - assets/26.m4a
    - assets/27.mp3
    - assets/28.mp3
    - assets/29.m4a
    - assets/30.mp3
    - assets/gorge3.jpg
    - assets/gorge4.jpg
